require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Pherapeutic' do

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GoogleSignIn', '~> 5.0.2'
  
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
 
  
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-agora', :path => '../node_modules/react-native-agora'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'PherapeuticTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Pherapeutic-tvOS' do
  # Pods for Pherapeutic-tvOS

  target 'Pherapeutic-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
